

name: First Github Action Workflow
on:
    workflow_dispatch: 
jobs:
   welcome:
       runs-on: ubuntu-latest
       steps:
           - name: Print Welcome message
             run: echo "Welcome to git hub Action"
      
