name: Push Trigger Workflow
on:
  push:
    branches:
      - main
 jobs:
   push-job:
     runs-on: ubuntu-latest
     steps:
      - name: Print Message
        run: echo "Code was pushed to the main branch."
       - name: Display Date and Time
         run: date
        -name: Display Working directiory
          run: pwd
        
     
